
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action JouerAction;

	private global::Gtk.Action ChargerAction;

	private global::Gtk.Action AideAction;

	private global::Gtk.Action QuitterAction;

	private global::Gtk.Action NouvellePartieAction;

	private global::Gtk.Action ChargerUnePartieAction;

	private global::Gtk.Action RglesDuJeuAction;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.MenuBar menubar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.JouerAction = new global::Gtk.Action("JouerAction", global::Mono.Unix.Catalog.GetString("Jouer"), null, null);
		this.JouerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Jouer");
		w1.Add(this.JouerAction, null);
		this.ChargerAction = new global::Gtk.Action("ChargerAction", global::Mono.Unix.Catalog.GetString("Charger"), null, null);
		this.ChargerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Charger");
		w1.Add(this.ChargerAction, null);
		this.AideAction = new global::Gtk.Action("AideAction", global::Mono.Unix.Catalog.GetString("Aide "), null, null);
		this.AideAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Aide ");
		w1.Add(this.AideAction, null);
		this.QuitterAction = new global::Gtk.Action("QuitterAction", global::Mono.Unix.Catalog.GetString("Quitter"), null, null);
		this.QuitterAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Quitter");
		w1.Add(this.QuitterAction, null);
		this.NouvellePartieAction = new global::Gtk.Action("NouvellePartieAction", global::Mono.Unix.Catalog.GetString("Nouvelle partie"), null, null);
		this.NouvellePartieAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Nouvelle partie");
		w1.Add(this.NouvellePartieAction, null);
		this.ChargerUnePartieAction = new global::Gtk.Action("ChargerUnePartieAction", global::Mono.Unix.Catalog.GetString("Charger une partie"), null, null);
		this.ChargerUnePartieAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Charger une partie");
		w1.Add(this.ChargerUnePartieAction, null);
		this.RglesDuJeuAction = new global::Gtk.Action("RglesDuJeuAction", global::Mono.Unix.Catalog.GetString("Règles du jeu "), null, null);
		this.RglesDuJeuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Règles du jeu ");
		w1.Add(this.RglesDuJeuAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='JouerAction' action='JouerAction'><menuitem name='NouvellePartieAction' action='NouvellePartieAction'/></menu><menu name='ChargerAction' action='ChargerAction'><menuitem name='ChargerUnePartieAction' action='ChargerUnePartieAction'/></menu><menu name='AideAction' action='AideAction'><menuitem name='RglesDuJeuAction' action='RglesDuJeuAction'/></menu><menu name='QuitterAction' action='QuitterAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.fixed1.Add(this.menubar1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.menubar1]));
		w2.X = 11;
		w2.Y = 12;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 540;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
